import glob
import pandas as pd
from snakemake.utils import validate
from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.4.1")


##### setup report #####
configfile: "config/config.yaml"


# report: "report/workflow.rst" ## Why this?


##### load rules #####


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trim.smk"
include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/aserc.smk"

##### target rules #####

rule all:
    input:
        get_final_output(),
