import glob
import pandas as pd
from snakemake.utils import validate
from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.4.1")


##### setup report #####
configfile: "config/config.yaml"


# report: "report/workflow.rst" ## Why this?


##### load rules #####


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trim.smk"
include: "rules/qc.smk"
include: "rules/align.smk"

##### target rules #####

sample_file=(
    pd.read_csv(config["samples"], sep="\t", dtype={"sample": str})
    .set_index("sample", drop=False)
    .sort_index()
)
SAMPLES=sample_file['sample'].tolist()

rule all:
    input:
        expand("results/star_2p/{sample}_ReadsPerGene.out.tab",sample=SAMPLES),
        qc="qc/multiqc.html"
        if config["compute_aserc"]:
            expand("results/aserc/{sample}_aserc.csv",sample=SAMPLES)