# path or URL to sequencing sample sheet (TSV format, columns: sample, fq1, fq2)
samples: config/samples.tsv

# path to reference genome fasta
ref_genome: resources/Lerg_assemblyV1.fasta

# path to reference annotation in gtf format
ref_annotation: resources/merged.sort.gtf

# path to the vcf of variants you want counts from
compute_aserc: True
snp_vcf: resources/Lerg_assemblyV1_E_LergOnly.AlleleFilter2.BestSNPs.recode.vcf

# add the ENCODE options for STAR
params:
  star: "--outFilterType BySJout --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000"