$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string

  ref_genome:
    type: string

  ref_annotation:
    type: string

  params:
    type: object
    properties:
      star: 
        type: string
    required:
      - star

required:
  - samples
  - ref_genome
  - ref_annotation
  - params
